### ISSUE TITLE
Slightly misaligned icons

### ISSUE THREAD

**Issue by yhoiseth** [chniter/bstreeview#1]
Sweet project! I noticed a slight icon misalignment.

**Describe the bug**

The top drawer icon is slightly more to the left than the two drawer icons below.

**To Reproduce**
1. Go to https://chniter.github.io/bstreeview/
2. Click on "Inbox"
3. Click on "Office"

**Expected behavior**
Icons are aligned.

**Screenshots**
<img width="584" alt="Screenshot 2020-02-28 at 13 12 04" src="https://user-images.githubusercontent.com/8469540/75547822-14aa7e00-5a2c-11ea-85e3-afa874a1de81.png">

**Desktop (please complete the following information):**
 - OS:  macOS Catalina
 - Browser: Firefox
 - Version: 73.0.1 (64-bit)

**Additional context**

Perhaps https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons could be helpful.

**Comment by chniter** [comment]
Hello,

Thank you for posting the first enhacement.
Glad to know that you appreciate this project.
I will fix this icon misalignment.

**Comment by chniter** [comment]
Done see new release https://github.com/chniter/bstreeview/releases/tag/v1.2.0
