### ISSUE TITLE
Remove margin-left for better accessibility

### ISSUE THREAD

**Issue by githubcom13** [chniter/bstreeview#13]
For better accessibility the first parent elements should not have a margin on the left. 

How to remove the margin of the first element to get this?

ex. [https://zupimages.net/up/20/17/5mav.png](https://zupimages.net/up/20/17/5mav.png)

**Comment by chniter** [comment]
Hello,
See the new release v1.2.0.
https://github.com/chniter/bstreeview#parentsmarginleft
