### ISSUE TITLE
Missing ARIA attributes

### ISSUE THREAD

**Issue by xi** [chniter/bstreeview#2]
To provide hints for assitive technologies, this should use ARIA attributes as described here: https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView

**Comment by chniter** [comment]
Hello,

It's very good to know, I'll put that as a task to do in the next version.

Thank you, glad to read your feeback!

**Comment by chniter** [comment]
Done, see new release https://github.com/chniter/bstreeview/releases/tag/v1.2.0

**Comment by xi** [comment]
There still seem to be some issues in the implementation. Specifically, the following rules from the spec are not met:

- All tree nodes are contained in or owned by an element with role tree.
-  Each element with role treeitem that serves as a parent node has aria-expanded set to false when the node is in a closed state and set to true when the node is in an open state. End nodes do not have the aria-expanded attribute because, if they were to have it, they would be incorrectly described to assistive technologies as parent nodes. 
- If the tree does not support multiple selection, aria-selected is set to true for the selected node and it is not present on any other node in the tree.
- The element with role tree has either a visible label referenced by aria-labelledby or a value specified for aria-label.

I understand that it is hard to implement all of this. But I am not sure if doing only some parts and leaving out the rest makes things better or worse.

**Comment by chniter** [comment]
Hello @xi,
I implemented what i see more interesting, i try to implement other option if necessary.
