### ISSUE TITLE
Pass an array instead of a JSON string

### ISSUE THREAD

**Issue by igorbasko01** [chniter/bstreeview#3]
**Is your feature request related to a problem? Please describe.**
Currently the `bstreeview` expects a string when passing `data` value. It wasn't clear for me from the `README` file that it expected a JSON string.

**Describe the solution you'd like**
Would it be better to pass an array filled with dictionaries instead?

**Describe alternatives you've considered**
Also it is possible to update the `README` file instead, that it would be clear that a JSON string should be passed.

**Comment by chniter** [comment]
Hello,

Thanks for feedback.
Yes i have to pass array instead.

**Comment by igorbasko01** [comment]
Would you like that I will make the change?

**Comment by chniter** [comment]
Any help is welcome :)

**Comment by chniter** [comment]
Big thanks to @igorbasko01  for help !
