### ISSUE TITLE
Error running unminified js

### ISSUE THREAD

**Issue by Flyer53** [chniter/bstreeview#5]
First of all thanks for this project 👍 

**Describe the bug**
Running the unminified js file causes an error (I tried on desktop FF and Chrome)
![bstreeview 2020-03-09 092047](https://user-images.githubusercontent.com/6769021/76196110-f1c95800-61e9-11ea-9ce5-3876b7aada30.png)
In order to contribute it would be great if I could run the unminified js file.

Thanks,
Stefan

**Comment by chniter** [comment]
Hello,

Thanks for feedback 👍 
You downloaded the release v1.0.0 or you are trying the plugin from the Master brunch?

**Comment by Flyer53** [comment]
Hi Sami,
Thanks for the quick reply... and yes, I downloaded the master branch.
I wanted to add some code so that each nav item gets a customized `href` attribute value. But maybe you have that already on your todo list :smirk:

**Comment by chniter** [comment]
Yes, i will add  `href` attribute into option parameter.
I will check the error iof the unminified js file.
Try to download the release v1.0.0. It work fine.

**Comment by chniter** [comment]
After testing the unminified js file, i haven't the erro, can you share with me more details about the example that you are doing?

**Comment by Flyer53** [comment]
I can confirm that the file from the _bstreeview-1.0.0.zip_ download works without error while the file from _bstreeview-master.zip_ causes the error. I compared the two bstreeview.js files and found they are different in spite of having the same version number.

![bstreeview](https://user-images.githubusercontent.com/6769021/76251543-74343500-6247-11ea-9488-4bd09f0c0a16.png)

Adding the missing line of code to the one file eliminates the error.

**Comment by chniter** [comment]
Hi Stefan,

Thanks for details.
I will check this.
👍

**Comment by Flyer53** [comment]
My pleasure Sami,

One more proposal:
I think it would also be a good idea to be able to add a custom css class to the individual nav items. So you could add custom styles depending on menu level.

**Comment by chniter** [comment]
Nice idea!

**Comment by chniter** [comment]
Another @Flyer53  done staff !
